import { Injectable, inject, signal } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { InputField } from 'src/app/core/shared/common/forms/core/builders/input.builder';
import { DropdownField } from 'src/app/core/shared/common/forms/core/builders/dropdown.builder';
import { TabBuilder } from 'src/app/core/shared/common/forms/core/builders/tab.builder';
import { AllowanceMasterEnum } from 'src/app/core/shared/common/enum/masters_enum/allowance-master-enum';
import { AllowanceMasterModel } from 'src/app/core/shared/common/model/masters/allowance-master.model';

const ALLOWANCE_TYPE_OPTIONS = [
    { label: 'Fixed Per Day',              value: 'fixed_per_day' },
    { label: 'Fixed Per Shift',            value: 'fixed_per_shift' },
    { label: 'Fixed Per Attendance',       value: 'fixed_per_attendance' },
    { label: 'Hourly',                     value: 'hourly' },
    { label: 'Percentage of Basic Salary', value: 'percentage_basic' },
    { label: 'Percentage of Daily Wage',   value: 'percentage_daily_wage' },
    { label: 'Per Trip',                   value: 'per_trip' },
    { label: 'Per Kilometre',              value: 'per_kilometre' },
    { label: 'Per Mobilization',           value: 'per_mobilization' },
    { label: 'Per Demobilization',         value: 'per_demobilization' },
    { label: 'Per Operating Hour',         value: 'per_operating_hour' },
    { label: 'Per Standby Hour',           value: 'per_standby_hour' },
    { label: 'Per Productive Hour',        value: 'per_productive_hour' },
    { label: 'Monthly Fixed',              value: 'monthly_fixed' },
    { label: 'Rotation-Based',             value: 'rotation_based' },
];

@Injectable({
  providedIn: 'root',
})
export class AllowanceMasterFormConfig {
  private translate = inject(TranslateService);

  public readonly AllowanceMasterForm =
    () =>
    (dataFromComponent?: any, initialData?: AllowanceMasterModel, isEditMode?: boolean, data?: AllowanceMasterModel) => {
      initialData = new AllowanceMasterModel();
      return [
        new TabBuilder(this.translate)
          .addTabFields([
            {
              tabHeader: this.translate.instant('allowanceMasterDetails_TC'),
              fields: [
                new InputField(
                  this.translate,
                  AllowanceMasterEnum.allowance_code,
                  isEditMode,
                  data,
                  initialData,
                  undefined,
                  this.translate.instant('autogeneratedField_TC'),
                )
                  .addFieldWidth('32%')
                  .isReadOnly(true)
                  .toObject(),

                new InputField(
                  this.translate,
                  AllowanceMasterEnum.allowance_name,
                  isEditMode,
                  data,
                  initialData,
                )
                  .addFieldWidth('32%')
                  .validate(true, 1, 100)
                  .toObject(),

                new DropdownField(
                  this.translate,
                  AllowanceMasterEnum.allowance_type,
                  isEditMode,
                  data,
                  initialData,
                  false,
                )
                  .addFieldWidth('32%')
                  .addKeyValueLabel('label', 'value')
                  .getOptions(signal(ALLOWANCE_TYPE_OPTIONS))
                  .toObject(),

                new InputField(
                  this.translate,
                  AllowanceMasterEnum.unit_rate,
                  isEditMode,
                  data,
                  initialData,
                )
                  .addFieldWidth('32%')
                  .inputType('number')
                  .toObject(),
              ],
            },
          ])
      ];
    };
}
