import { Injectable, inject } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { InputField } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/input.builder';
import { NumberField } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/number.builder';
import { TabBuilder } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/tab.builder';
import { TextBuilder } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/textarea.builder';
import { ApiService } from 'src/app/core/services/api.service';
import { DepartmentEnum } from 'src/app/modules/hrm-shared/core/shared/common/enum/masters_enum/department-enum';
import { DepartmentModel } from 'src/app/modules/hrm-shared/core/shared/common/model/masters/department.model';


@Injectable({
  providedIn: 'root',
})
export class DepartmentFormConfig {
  private translate = inject(TranslateService);
  private apiService = inject(ApiService);

  public readonly departmentForm =
    () =>
    (dataFromComponent?:any, initialData?: DepartmentModel, isEditMode?: boolean, data?: DepartmentModel) => {
      initialData = new DepartmentModel();
      return [
        new TabBuilder(this.translate)
        .addTabFields([
          {
            tabHeader: this.translate.instant('departmentDetails_TC'),
            fields: [
                new InputField(this.translate,DepartmentEnum.department_code,isEditMode,data,initialData,undefined,this.translate.instant('autogeneratedField_TC'))
                .addFieldWidth('48%')
                .isReadOnly(true)
                .toObject(),
                new InputField(this.translate,DepartmentEnum.department_name,isEditMode,data,initialData)
                .addFieldWidth('48%')
                .validate(true, 1, 100)
                .toObject(),
                new NumberField(this.translate,DepartmentEnum.order,isEditMode,data,initialData)
                .addFieldWidth('24%')
                .validate(false)
                .toObject(),
            ],
          }
        ])
      ];
    };
}
