import { Injectable, inject } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { InputField } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/input.builder';
import { TabBuilder } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/tab.builder';
import { ApiService } from 'src/app/core/services/api.service';
import { DesignationModel } from 'src/app/modules/hrm-shared/core/shared/common/model/masters/designation.model';
import { DesignationEnum } from 'src/app/modules/hrm-shared/core/shared/common/enum/masters_enum/designation.enum';


@Injectable({
  providedIn: 'root',
})
export class DesignationFormConfig {
  private translate = inject(TranslateService);
  private apiService = inject(ApiService);

  public readonly DesignationForm =
    () =>
    (dataFromComponent?:any, initialData?: DesignationModel, isEditMode?: boolean, data?: DesignationModel) => {
      initialData = new DesignationModel();
      return [
        new TabBuilder(this.translate)
        .addTabFields([
          {
            tabHeader: this.translate.instant('designationDetails_TC'),
            fields: [
                new InputField(this.translate, DesignationEnum.designation_code, isEditMode, data, initialData, undefined, this.translate.instant('autogeneratedField_TC'))
                .addFieldWidth('48%')
                .isReadOnly(true)
                .toObject(),
                new InputField(this.translate, DesignationEnum.designation_name, isEditMode, data, initialData)
                .addFieldWidth('48%')
                .validate(true, 1, 100)
                .toObject(),   
            ],
          }
        ])
      ];
    };
}
