import { Injectable, inject, signal } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { InputField } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/input.builder';
import { TabBuilder } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/tab.builder';
import { DropdownField } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/dropdown.builder';
import { GradeMasterModel } from 'src/app/modules/hrm-shared/core/shared/common/model/masters/grade-master.model';
import { GradeMasterEnum } from 'src/app/modules/hrm-shared/core/shared/common/enum/masters_enum/grade-master.enum';
import { TextBuilder } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/textarea.builder';

@Injectable({
    providedIn: 'root',
})
export class GradeMasterFormConfig {
    private translate = inject(TranslateService);

    materialType = signal([
        { id: 'Stainless Steel', name: 'Stainless Steel' },
        { id: 'Super Duplex Steel', name: 'Super Duplex Steel' },
        { id: 'Lean Duplex Steel', name: 'Lean Duplex Steel' },
        { id: 'Low Carbon steel', name: 'Low Carbon steel' },
        { id: 'High Carbon Steel', name: 'High Carbon Steel' },
        { id: 'Alloy Steel', name: 'Alloy Steel' },
        { id: 'Non Alloy Steel', name: 'Non Alloy Steel' },
        { id: 'Nickel Steel', name: 'Nickel Steel' },
        { id: 'Cast Iron and SG Iron', name: 'Cast Iron and SG Iron' },
      ]);

    public readonly GradeMasterForm =
        () =>
            (dataFromComponent?: any, initialData?: GradeMasterModel, isEditMode?: boolean, data?: GradeMasterModel) => {
                initialData = new GradeMasterModel();
                initialData = { ...initialData, ...data };
                return [
                    new TabBuilder(this.translate)
                        .addTabFields([
                            {
                                tabHeader: this.translate.instant('gradeDetails_TC'),
                                fields: [
                                    new InputField(this.translate, GradeMasterEnum.gradeCode, isEditMode, data, initialData, undefined, this.translate.instant('autogeneratedField_TC'))
                                        .addFieldWidth('35%')
                                        .isReadOnly(true)
                                        .toObject(),
                                    new InputField(this.translate, GradeMasterEnum.gradeName, isEditMode, data, initialData)
                                        .addFieldWidth('35%')
                                        .validate(true, 1, 250)
                                        .toObject(),
                                    new TextBuilder(this.translate, GradeMasterEnum.gradeSpecification, isEditMode, data, initialData)
                                        .addFieldWidth('24%')
                                        .toObject(),
                                    new InputField(this.translate, GradeMasterEnum.refGrade, isEditMode, data, initialData)
                                        .addFieldWidth('35%')
                                        .validate(false, 1, 250)
                                        .toObject(),
                                    new DropdownField(this.translate, GradeMasterEnum.materialType, isEditMode, data, initialData, false, 'formSelectPlaceholder_SC')
                                        .addFieldWidth('24%')
                                        .variantType('basic')
                                        .addKeyValueLabel('name', 'id')
                                        .isNeedFilter(false)
                                        .getOptions(this.materialType)
                                        .toObject(),
                                ],
                            }
                        ])
                ];
            };

}
