import { Injectable, inject, signal } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { InputField } from 'src/app/core/shared/common/forms/core/builders/input.builder';
import { TabBuilder } from 'src/app/core/shared/common/forms/core/builders/tab.builder';
import { DummyField } from 'src/app/core/shared/common/forms/core/builders/dummy.builder';
import { OverlayPanelBuilder, TableBuilder } from 'src/app/core/shared/common/forms/core/builders/table.builder';
import { ApiService } from 'src/app/core/services/api.service';
import {
  GradeGrossDeductionsModel,
  GradeGrossEarningsModel,
  GradeModel,
} from 'src/app/core/shared/common/model/masters/grade.model';
import {
  GradeEnum,
  GradeGrossDeductionsEnum,
  GradeGrossEarningsEnum,
} from 'src/app/core/shared/common/enum/masters_enum/grade.enum';
import { SalaryCalculationComponent } from 'src/app/modules/hrm-main/salary-calculation/salary-calculation.component';
import { SalaryComponentsEnum } from 'src/app/core/shared/common/enum/masters_enum/salary-components-enum';
import { ServiceUrlConstants } from 'src/app/core/shared/utils/service-url-constants';
import { SalaryComponentsModel } from 'src/app/core/shared/common/model/masters/salary-components.model';

@Injectable({
  providedIn: 'root',
})
export class GradeFormConfig {
  private translate = inject(TranslateService);
  private apiService = inject(ApiService);
  private readonly grossItemFooterInitialize = signal([]);
  private readonly deductionsItemFooterInitialize = signal([]);
  fixedGrossEarningList: any = signal([])
  fixedGrossDeductionsList: any = signal([])
  public readonly GradeForm =
    () =>
      (dataFromComponent?: any, initialData?: GradeModel, isEditMode?: boolean, data?: GradeModel) => {
        initialData = new GradeModel();

        const grade_gross_earnings = isEditMode ? data?.grade_gross_earnings || [] : [];
        const grade_gross_deductions = isEditMode ? data?.grade_gross_deductions || [] : [];

        if (grade_gross_earnings?.length) {
          this.grossUpdateTableFooterValues(data);
        } else {
          this.grossesItemFooterInitialize();
        }

        if (grade_gross_deductions?.length) {
          this.deductionUpdateTableFooterValues(data);
        } else {
          this.deductionItemFooterInitialize();
        }

        return [
          new TabBuilder(this.translate).addTabFields([
            {
              tabHeader: this.translate.instant('gradeInformation_TC'),
              fields: [
                new InputField(this.translate, GradeEnum.grade_code, isEditMode, data, initialData,undefined, this.translate.instant('autogeneratedField_TC'))
                  .addFieldWidth('24%')
                  .isReadOnly(true)
                  .validate(false, 1, 100)
                  .toObject(),
                new InputField(this.translate, GradeEnum.grade_description, isEditMode, data, initialData)
                  .addFieldWidth('24%')
                  .validate(true, 1, 100)
                  .toObject(),
                new DummyField(this.translate, GradeEnum.grossMontlyTotal, isEditMode, data, initialData)
                  .isFieldHidden(true)
                  .toObject(),
                new DummyField(this.translate, GradeEnum.grossYearlyTotal, isEditMode, data, initialData)
                  .isFieldHidden(true)
                  .toObject(),
                new DummyField(this.translate, GradeEnum.deductionMontlyTotal, isEditMode, data, initialData)
                  .isFieldHidden(true)
                  .toObject(),
                new DummyField(this.translate, GradeEnum.deductionYearlyTotal, isEditMode, data, initialData)
                  .isFieldHidden(true)
                  .toObject(),
                {
                  type: 'accordion',
                  multiple: true,
                  fields: [
                    {
                      // @ts-ignore
                      accordionHeader: this.translate.instant('grossEarnings_TC'),
                      fieldUniqueKey: 'gross-earnings',
                      selected: true,
                      fields: [
                        new TableBuilder(this.translate, GradeEnum.GradegrossEarnings, '', true)
                          .columnSchema([
                            { name: GradeGrossEarningsEnum.components + '_TC', colWidth: '200px' },
                            { name: GradeGrossEarningsEnum.monthly + '_TC', colWidth: '200px' },
                            { name: GradeGrossEarningsEnum.yearly + '_TC', colWidth: '200px' },
                          ])
                          .formInitialise<GradeGrossEarningsModel>(new GradeGrossEarningsModel())
                          .formSchema([
                            { name: GradeGrossEarningsEnum.components, type: 'input' },
                            {
                              name: GradeGrossEarningsEnum.monthly,
                              type: 'number',
                              onValueChange: this.onChangeCalculationFields.bind(this),
                              updateTableFooter: this.grossUpdateTableFooterValues.bind(this),
                              minFractionDigits: 0,
                              maxFractionDigits: 0,
                            },
                            {
                              name: GradeGrossEarningsEnum.yearly,
                              type: 'number',
                              readonly: true,
                              minFractionDigits: 0,
                              maxFractionDigits: 0,
                            },
                          ])
                          .getDatasource<Array<GradeGrossEarningsModel>>('id', grade_gross_earnings)
                          .enableFooter(true)
                          .setTableWidth('90vw')
                          .setTableCaption(true)
                          .setCheckBox(false)
                          .setTableCaptionDialogButton(true)
                          .setTableCaptionDialogButtonLabel("Add Allowance Details")
                          .setField(
                            new OverlayPanelBuilder()
                              .setTableName(GradeEnum.GradegrossEarnings)
                              .setOverlayPanelColumnSchema([
                                { name: this.translate.instant(`${SalaryComponentsEnum.component}_TC`), field: SalaryComponentsEnum.component },

                              ])
                              .setOnUpdateRows(this.updateTableRowsEarnings.bind(this))
                              .setOverlayPanelSelectionMode('single')
                              .setOverlayPanelRows(10)
                              .setDialogScrollHeight('55vh')
                              .setOverlayPanelFormInitialise([SalaryComponentsEnum.component])
                              .setOverlayPanelPaginator(true)
                              .setScrollable(true)
                              .setLazy(true)
                              .setFontSize('14px')
                              .setQueryParams({
                                type: 'Allowance',
                                is_active: true,
                                search_key: `${SalaryComponentsEnum.component}`,
                              })
                              .setDisabledField('false')
                              // .setOverlayPanelSelectedArray(this.selectedJobCardList)
                              .setUrls(`${ServiceUrlConstants.SALARY_COMPONET_CRUD}`)
                              .setOverlayDialogConfig({ width: '35vw', height: '75vh' })
                              .build()
                          )
                          .setAddButton(true)
                          .footerInitialise(this.grossItemFooterInitialize())
                          .onDeleteTableRow(this.grossUpdateTableFooterValues.bind(this))
                          .build(),
                      ],
                    },
                    {
                      // @ts-ignore
                      accordionHeader: this.translate.instant('grossDeductions_TC'),
                      fieldUniqueKey: 'gross-deductions',
                      selected: true,
                      fields: [
                        new TableBuilder(this.translate, GradeEnum.GradegrossDeductions, '', true)
                          .columnSchema([
                            { name: GradeGrossDeductionsEnum.components + '_TC', colWidth: '200px' },
                            { name: GradeGrossDeductionsEnum.monthly + '_TC', colWidth: '200px' },
                            { name: GradeGrossDeductionsEnum.yearly + '_TC', colWidth: '200px' },
                          ])
                          .formInitialise<GradeGrossDeductionsModel>(new GradeGrossDeductionsModel())
                          .formSchema([
                            { name: GradeGrossDeductionsEnum.components, type: 'input' },
                            {
                              name: GradeGrossDeductionsEnum.monthly,
                              type: 'number',
                              onValueChange: this.onChangeCalculationFields.bind(this),
                              updateTableFooter: this.deductionUpdateTableFooterValues.bind(this),
                              minFractionDigits: 0,
                              maxFractionDigits: 0,
                            },
                            {
                              name: GradeGrossDeductionsEnum.yearly,
                              type: 'number',
                              readonly: true,
                              minFractionDigits: 0,
                              maxFractionDigits: 0,
                            },
                          ])
                          .getDatasource<Array<GradeGrossDeductionsModel>>('id', grade_gross_deductions)
                          .enableFooter(true)
                          .setTableWidth('90vw')
                          .setTableCaption(true)
                          .setCheckBox(false)
                          .setTableCaptionDialogButton(true)
                          .setTableCaptionDialogButtonLabel("Add Deduction Details")
                          .setField(
                            new OverlayPanelBuilder()
                              .setTableName(GradeEnum.GradegrossDeductions)
                              .setOverlayPanelColumnSchema([
                                { name: this.translate.instant(`${SalaryComponentsEnum.component}_TC`), field: SalaryComponentsEnum.component },

                              ])
                              .setOnUpdateRows(this.updateTableRowsDeduction.bind(this))
                              .setOverlayPanelSelectionMode('single')
                              .setOverlayPanelRows(10)
                              .setDialogScrollHeight('55vh')
                              .setOverlayPanelFormInitialise([SalaryComponentsEnum.component])
                              .setOverlayPanelPaginator(true)
                              .setScrollable(true)
                              .setLazy(true)
                              .setFontSize('14px')
                              .setQueryParams({
                                type: 'Deduction',
                                is_active: true,
                                search_key: `${SalaryComponentsEnum.component}`,
                              })
                              .setDisabledField('false')
                              // .setOverlayPanelSelectedArray(this.selectedJobCardList)
                              .setUrls(`${ServiceUrlConstants.SALARY_COMPONET_CRUD}`)
                              .setOverlayDialogConfig({ width: '35vw', height: '75vh' })
                              .build()
                          )
                          .setAddButton(true)
                          .footerInitialise(this.deductionsItemFooterInitialize())
                          .onDeleteTableRow(this.deductionUpdateTableFooterValues.bind(this))
                          .build(),

                      ],
                    },
                  ],
                },
              ],
            },
          ]),
        ];
      };


  // TABLE ADD Deduction
  updateTableRowsDeduction(rows: SalaryComponentsModel[]) {
    // console.log('updateTableRows', rows);
    return rows.map((row: SalaryComponentsModel) => {
      // console.log("row on selection", row)
      let GradeDeductionDetailsItem: GradeGrossDeductionsModel = new GradeGrossDeductionsModel();
      GradeDeductionDetailsItem.id = this.generateUniqueId();
      GradeDeductionDetailsItem.table_row_id = row.id;
      GradeDeductionDetailsItem.components = row.component;
      GradeDeductionDetailsItem.monthly = 0;
      GradeDeductionDetailsItem.yearly = 0;
      GradeDeductionDetailsItem.salary_component = row.id;
      return GradeDeductionDetailsItem
    })
  }

  // TABLE ADD Earnings
  updateTableRowsEarnings(rows: SalaryComponentsModel[]) {
    // console.log('updateTableRows', rows);
    return rows.map((row: SalaryComponentsModel) => {
      // console.log("row on selection", row)
      let GradeEarningsDetailsItem: GradeGrossEarningsModel = new GradeGrossEarningsModel();
      GradeEarningsDetailsItem.id = this.generateUniqueId();
      GradeEarningsDetailsItem.table_row_id = row.id;
      GradeEarningsDetailsItem.components = row.component;
      GradeEarningsDetailsItem.monthly = 0;
      GradeEarningsDetailsItem.yearly = 0;
      GradeEarningsDetailsItem.salary_component = row.id;
      return GradeEarningsDetailsItem
    })
  }
  generateUniqueId() {
    return Math.floor(1000000000000 + Math.random() * 9000) + 'A';
  }

  grossUpdateTableFooterValues(data: GradeModel) {
    let totalGrossMonthly = 0;
    let totalGrossYearly = 0;

    data.grade_gross_earnings?.forEach((element) => {
      totalGrossMonthly += Number(element?.monthly ?? 0);
      totalGrossYearly += Number(element?.yearly ?? 0);
    });

    const footer = this.generateFooter(GradeGrossEarningsEnum, totalGrossMonthly, totalGrossYearly);
    data.gross_monthly_total = Number(Math.round(totalGrossMonthly));
    data.gross_yearly_total = Number(Math.round(totalGrossYearly));
    console.log('footer', data);
    this.grossItemFooterInitialize.set(footer);
    return { form: data, footerInitialize: footer };
  }

  deductionUpdateTableFooterValues(data: GradeModel) {
    let totalMonthly = 0;
    let totalYearly = 0;

    data.grade_gross_deductions?.forEach((element) => {
      totalMonthly += Number(element?.monthly ?? 0);
      totalYearly += Number(element?.yearly ?? 0);
    });

    const footer = this.generateFooter(GradeGrossEarningsEnum, totalMonthly, totalYearly);
    data.deduction_monthly_total = Number(Math.round(totalMonthly));
    data.deduction_yearly_total = Number(Math.round(totalYearly));
    this.deductionsItemFooterInitialize.set(footer);
    return { form: data, footerInitialize: footer };
  }

  onChangeCalculationFields(value: any, item: GradeGrossEarningsModel, formValue: GradeModel, formFields: any, field: any) {
    item.yearly = Number((Number(item.monthly || 0) * 12).toFixed(2));
    return item;
  }

  grossesItemFooterInitialize() {
    this.grossItemFooterInitialize.set([
      { name: 'Total' },
      { name: '' },
      { name: 0 },
      { name: 0 },
    ]);
  }

  deductionItemFooterInitialize() {
    this.deductionsItemFooterInitialize.set([
      { name: 'Total' },
      { name: '' },
      { name: 0 },
      { name: 0 },
    ]);
  }

  private generateFooter(enumObj: any, monthlyTotal: number, yearlyTotal: number) {
    const keys = Object.values(enumObj);
    const footer = keys.map((key, index) => {
      if (index === 0) return { name: 'Total' };
      if (key === GradeGrossEarningsEnum.monthly) return { name: monthlyTotal.toFixed(3) };
      if (key === GradeGrossEarningsEnum.yearly) return { name: yearlyTotal.toFixed(3) };
      return { name: '' };
    });
    footer.push({ name: '' });
    return footer;
  }






}
