import { Injectable, inject, signal } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { ShiftMasterModel } from 'src/app/modules/hrm-shared/core/shared/common/model/masters/shift-master.model';
import { TabBuilder } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/tab.builder';
import { InputField } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/input.builder';
import { ShiftMasterEnum } from 'src/app/modules/hrm-shared/core/shared/common/enum/masters_enum/shift-enum';
import { DropdownField } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/dropdown.builder';
import { TextBuilder } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/textarea.builder';
import { DateField } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/date.builder';
import { ToggleBuilder } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/toggle.builder';
import { NumberField } from 'src/app/modules/hrm-shared/core/shared/common/forms/core/builders/number.builder';

@Injectable({
    providedIn: 'root',
})
export class ShiftMasterFormConfig {
    private translate = inject(TranslateService);

    private readonly statusList = signal([
        { key: 'Active', value: 'active' },
        { key: 'Inactive', value: 'inactive' },
    ]);

    private readonly otRoundingList = signal([
        { key: 'Nearest', value: 'nearest' },
        { key: 'Up', value: 'up' },
        { key: 'Down', value: 'down' },
    ]);

    public readonly ShiftMasterForm =
        () =>
            (dataFromComponent?: any, initialData?: ShiftMasterModel, isEditMode?: boolean, data?: ShiftMasterModel) => {
                initialData = new ShiftMasterModel();
                // console.log("data",data)
                const defaultStatusObject = isEditMode ? { name: data?.status, id: data?.status } : { name: 'active', id: 'active' };
                const defaultOtRoundingObject = isEditMode ? { name: data?.ot_rounding, id: data?.ot_rounding } : { name: 'nearest', id: 'nearest' };

                return [
                    new TabBuilder(this.translate)
                        .addTabFields([
                            {
                                tabHeader: this.translate.instant('basicDetails_TC'),
                                fieldUniqueKey: 'basic-details',
                                fields: [
                                    new InputField(this.translate, ShiftMasterEnum.shift_code, isEditMode, data, initialData, undefined, this.translate.instant('autogeneratedField_TC'))
                                        .addFieldWidth('24%')
                                        .isReadOnly(true)
                                        .toObject(),
                                    new InputField(this.translate, ShiftMasterEnum.shift_name, isEditMode, data, initialData)
                                        .addFieldWidth('24%')
                                        .validate(true)
                                        .toObject(),
                                    new DropdownField(this.translate, ShiftMasterEnum.status, isEditMode, data, initialData, undefined)
                                        .addFieldWidth('24%')
                                        .addKeyValueLabel('key', 'value')
                                        .getOptions(this.statusList)
                                        .validate(false)
                                        .setDefaultObject(defaultStatusObject)
                                        .toObject(),
                                    new TextBuilder(this.translate, ShiftMasterEnum.notes, isEditMode, data, initialData)
                                        .addFieldWidth('49%')
                                        .toObject(),
                                ],
                            },
                            {
                                tabHeader: this.translate.instant('timingDetails_TC'),
                                fieldUniqueKey: 'timing-details',
                                fields: [
                                    {
                                        type: 'accordion',
                                        multiple: true,
                                        fields: [
                                            {
                                                accordionHeader: this.translate.instant('shiftTiming_TC'),
                                                selected: true,
                                                fields: [
                                                    // In your ShiftMasterFormConfig, ensure time fields are properly configured
                                                    new DateField(this.translate, ShiftMasterEnum.start_time, isEditMode, data, initialData, true)
                                                        .addFieldWidth('24%')
                                                        .addFormat('hh:mm')
                                                        .setShowClearIcon(false)
                                                        .validate(true)
                                                        .onChange(this.durationCalculation.bind(this))
                                                        // .setTimeOnly(true) // Use this instead of setShowTime for time-only fields
                                                        .toObject(),
                                                    new DateField(this.translate, ShiftMasterEnum.end_time, isEditMode, data, initialData, true)
                                                        .addFieldWidth('24%')
                                                        .addFormat('hh:mm')
                                                        .setShowClearIcon(false)
                                                        .onChange(this.durationCalculation.bind(this))
                                                        .validate(true)
                                                        .toObject(),
                                                    new ToggleBuilder(this.translate, ShiftMasterEnum.is_cross_midnight, isEditMode, data, initialData)
                                                        .addFieldWidth('24%')
                                                        .onChange(this.durationCalculation.bind(this))
                                                        .toObject(),
                                                ]
                                            },
                                            {
                                                accordionHeader: this.translate.instant('gracePeriod_TC'),
                                                selected: false,
                                                fields: [
                                                    new DateField(this.translate, ShiftMasterEnum.grace_period_in, isEditMode, data, initialData, true)
                                                        .addFieldWidth('24%')
                                                        .addFormat('hh:mm')
                                                        .validate(false)
                                                        .setShowClearIcon(false)
                                                        // .setTimeOnly(true) // Use this instead of setShowTime for time-only fields
                                                        .toObject(),
                                                    new DateField(this.translate, ShiftMasterEnum.grace_period_out, isEditMode, data, initialData, true)
                                                        .addFieldWidth('24%')
                                                        .addFormat('hh:mm')
                                                        .setShowClearIcon(false)
                                                        .validate(false)
                                                        // .setTimeOnly(true) // Use this instead of setShowTime for time-only fields
                                                        .toObject(),
                                                ]
                                            },
                                        ]
                                    },
                                ]
                            },
                            {
                                tabHeader: this.translate.instant('overtimeSettings_TC'),
                                fieldUniqueKey: 'overtime-settings',
                                fields: [
                                    new InputField(this.translate, ShiftMasterEnum.duration, isEditMode, data, initialData)
                                        .addFieldWidth('24%')
                                        .isReadOnly(true) // Make duration read-only as it should be calculated
                                        .toObject(),
                                    // new InputField(this.translate, ShiftMasterEnum.max_ot, isEditMode, data, initialData)
                                    //     .addFieldWidth('24%')
                                    //     .toObject(),

                                    new DateField(this.translate, ShiftMasterEnum.max_ot, isEditMode, data, initialData, true)
                                        .addFieldWidth('24%')
                                        .addFormat('hh:mm')
                                        .setShowClearIcon(false)
                                        .onChange(this.durationCalculation.bind(this))
                                        .validate(true)
                                        .toObject(),
                                    new NumberField(this.translate, ShiftMasterEnum.ot_multiplier, isEditMode, data, initialData)
                                        .addFieldWidth('24%')
                                        .setMinValue(0.5)
                                        .setMaxValue(3.0)
                                        .validate(false)
                                        .toObject(),
                                    new DropdownField(this.translate, ShiftMasterEnum.ot_rounding, isEditMode, data, initialData, undefined, 'formSelectPlaceholder_SC')
                                        .addFieldWidth('24%')
                                        .addKeyValueLabel('key', 'value')
                                        .getOptions(this.otRoundingList)
                                        .validate(false)
                                        .setDefaultObject(defaultOtRoundingObject)
                                        .toObject(),
                                ]
                            }
                        ])
                ];
            };

    durationCalculation(prev, next, formValue, formFields) {
        console.log("formvalue", formValue);
        const startTime = formValue[ShiftMasterEnum.start_time];
        const endTime = formValue[ShiftMasterEnum.end_time];
        const isCrossMidnight = formValue[ShiftMasterEnum.is_cross_midnight];

        if (!startTime || !endTime) {
            return null;
        }

        // Extract hours and minutes from Date objects
        const startHours = startTime.getHours();
        const startMinutes = startTime.getMinutes();
        const endHours = endTime.getHours();
        const endMinutes = endTime.getMinutes();

        // Create Date objects using the extracted time values
        const start = new Date();
        start.setHours(startHours, startMinutes, 0, 0);

        let end = new Date();
        end.setHours(endHours, endMinutes, 0, 0);

        // If end time is before start time and is_cross_midnight is true, add 24 hours
        if (isCrossMidnight && end < start) {
            end = new Date(end.getTime() + 24 * 60 * 60 * 1000);
        }

        // Calculate duration in milliseconds
        const durationMs = end.getTime() - start.getTime();

        // Convert to hours and minutes
        const hours = Math.floor(durationMs / (1000 * 60 * 60));
        const minutes = Math.floor((durationMs % (1000 * 60 * 60)) / (1000 * 60));

        // Format as HH:MM
        // const duration = `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}`;
        const duration = `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:00`;


        // Update the duration field
        return {
            [ShiftMasterEnum.duration]: duration
        };
    }

}