export enum EmployeeEnum {
  employeeCode = 'employee_code',
  biometricKey = 'biometric_key',
  employeeCardNumber = 'employee_card_number',
  title = 'title',
  firstName = 'first_name',
  lastName = 'last_name',
  fatherName = 'father_name',
  motherName = 'mother_name',
  employeeType = 'employee_type',
  detailedEmployeeType = "detailed_employee_type",
  countByLevel = "count_by_level",
  designation = 'designation',
  designationName = 'designation__designation_name',
  department = 'department',
  grade = "grade",
  defaultShift = 'default_shift',
  default_shift_new = 'default_shift_new',
  defaultShiftName = 'default_shift_name',
  weeklyOff = 'weekly_off',
  nationality = 'nationality',
  employeeGroup = "employee_group",
  deviceId = "device_id",
  firstReportingAuthority = 'first_reporting_authority',
  reportingAuthorityFirstName = 'report_authority_first_name',
  reportAuthorityLastName = 'report_authority_last_name',
  secondReportAuthority = 'second_reporting_authority',
  secondReportAuthorityFirstName = 'second_report_authority_first_name',
  secondReportAuthorityLastName = 'second_report_authority_last_name',
  groups = "groups",
  user = "user",
  userPassword = "user_password",
  userCreated = 'user_created',
  systemUser = "system_user",
  dob = 'dob',
  doj = 'doj',
  doc = 'doc',
  dor = 'dor',
  address = 'address',
  postalCode = 'postal_code',
  email = 'email',
  maritalStatus = 'marital_status',
  gender = 'gender',
  bloodGroup = 'blood_group',
  localMobileNumber = 'local_mobile_number',
  homeMobileNumber = 'home_mobile_number',
  religion = 'religion',
  bankName = 'bank_name',
  accountNumber = 'account_number',
  ibanNo = 'iban_no',
  ifscCode = 'ifsc_code',
  swiftCode = 'swift_code',
  nomineeRelationship = 'nominee_relationship',
  nomineeMobileNumber = "nominee_mobile_number",
  payout = 'payout',
  nomineeName = 'nominee_name',
  branch = 'branch',
  previousEmployments = "previous_employments",
  profileImage = "profile_image",

  passportImage = "passport_image",
  passportImageBack = 'passport_image_back',
  visaImage = "visa_image",
  emiratesImage = "emirates_image",
  emiratesImageBack = "emirates_image_back",
  labourcardImage = "labour_card_image",
  FHCImage = "fhc_image",
  insuranceImage = "insurance_image",

  employeeDocumentDetails = 'employee_documents_details',
  employeeNomineeDetails = 'employee_nominee_details',
  departmentName = 'department_name',
  passportNo = "passport_no",
  passportIssueDate = "passport_issue_date",
  passportExpiryDate = "passport_expiry_date",
  visaNo = "visa_no",
  visaIssueDate = "visa_issue_date",
  visaExpiryDate = "visa_expiry_date",
  emiratesIdNo = "emirates_id_no",
  emiratesIdIssueDate = "emirates_id_issue_date",
  emiratesIdExpiryDate = "emirates_id_expiry_date",
  labourCardNo = "labour_card_no",
  labourCardIssueDate = "labour_card_issue_date",
  labourCardExpiryDate = "labour_card_expiry_date",
  fhcNo = "fhc_no",
  fhcIssueDate = "fhc_issue_date",
  fhcExpiryDate = "fhc_expiry_date",
  autoPunch = "auto_punch",
  jobLossInsuranceNo = "job_loss_insurance_no",
  jobLossInsuranceIssueDate = "job_loss_insurance_issue_date",
  jobLossInsuranceExpiryDate = "job_loss_insurance_expiry_date",
  otRequired = "is_ot_eligible",
  reporting = 'reporting',
  isEligibleMorP = "eligible_for_parental_leave",
  resident = "resident",

  //driving license details
  license_number = 'license_number',
  permit_number = 'permit_number',
  issue_date_of_license = 'issue_date_of_license',
  expiry_date_of_license = 'expiry_date_of_license',
  sponsors = 'sponsors',
  //operator mechanic classification
  operator_driver = 'operator_driver',
  operator_type = 'operator_type',
  mechanic_technician = 'mechanic_technician',
  technician_type = 'technician_type',
  primary_equipment_specialization = 'primary_equipment_specialization',
  secondary_equipment_specialization = 'secondary_equipment_specialization',
  employee_status_is_active = 'employee_status_is_active',

  //basic details
  cicpa_number = 'cicpa_number',
  cicpa_name = 'cicpa_name',
  cicpa_location = 'cicpa_location',
  cicpa_expiry_date = 'cicpa_expiry_date',
  exchange_number = 'exchange_number',
  is_exchange_number = 'is_exchange_number',
  shift_details = 'shift_details',
  branch_master = 'branch_master',
  is_emirati = "is_emirati",

  is_under_leave = 'is_under_leave',

  note = 'note',

  wpsEstablishmentId = 'wps_establishment_id',
  paymentMethod = 'payment_method',
  accountType = 'account_type',
  bankRoutingNo = 'bank_routing_no',
}

export enum PreviousEmploymentDetailsEnum {
  companyName = "company_name",
  designation = "designation",
  location = "location",
  joinedDate = "joined_date",
  resignedDate = "resigned_date",
}

export enum LicDetailsEnum {
  policyNumber = "policy_number",
  amount = "amount"
}

export enum SecurityUserEnum {
  employee = "employee",
  password = "password",
}

export enum EmployeeNomineeDetailsEnum {
  nomineeRelationship = 'nominee_relationship',
  nomineeName = 'nominee_name',
  nomineeAadharNumber = 'nominee_aadhar_number',
  nomineeMobileNumber = 'nominee_mobile_number',
  nomineePercentage = 'nominee_percentage',
  passportExpiryDate = "passport_expiry_date",
  visaExpiryDate = "visa_expiry_date",
  emiratesIdExpiryDate = "emirates_id_expiry_date",
  labourCardExpiryDate = "labour_card_expiry_date",
  jobLossInsuranceExpiryDate = "job_loss_insurance_expiry_date",
}
