export enum LeaveEntryEnum {
    leaveType = 'leave_type',
    availableLeaves = 'available_leaves',
    fromDate = 'from_date',
    toDate = 'to_date',
    condition = 'condition',
    noOfDays = 'no_of_days',
    reason = 'reason',
    remarks = 'remarks',
    isLop = 'is_lop',
    compOffDate='comp_off_date',
    isCompOff='is_comp_off',
    travel_or_leave='travel_or_leave',
    holidayDays='holiday_days',
    weeklyOffDays='weekly_off_days',
    typeOfDays='type_of_days',
    certificate='certificate',
    weeklyOff = "weeklyOff",
    isReversal='is_reversal',
    leaveTypeDefaultObj='leave_type_default_object',
    employeeDefaultObj='employee_default_object',
    extendedToDate = 'extended_to_date',
    allowBeyondEligible = 'allow_beyond_eligible',
    lopDaysFromExtension = 'lop_days_from_extension',
    isPaidBeyond = 'is_paid_beyond',
}
