export enum LeaveReversalEnum {
    leaveType = 'leave_type',
    availableLeaves = 'available_leaves',
    fromDate = 'from_date',
    toDate = 'to_date',
    noOfDays = 'no_of_days',
    reverseFromDate = 'reverse_from_date',
    reverseToDate = 'reverse_to_date',
    reverseNoOfDays = 'reverse_no_of_days',
    reason = 'reason',
    travel_or_leave = 'travel_or_leave',
    typeOfDays = 'type_of_days',
    employee = 'employee',
    leaveEntry = 'leave_entry',
    leaveApplication = 'leave_application',
    reasonForReversal = 'reason_for_reversal',
    leaveTypeDefaultObj = 'leave_type_default_object',
    employeeDefaultObj = 'employee_default_object',
    condition = 'condition',
    balanceNoOfDays = 'balance_no_of_days',
    defaultDelegatedReviewerObj = 'default_delegated_reviewer_obj',
    delegatedReviewer = 'delegated_reviewer',
    initiatorReviewer='initiator_reviewer',
    weeklyOff='weekly_off',
    includeHolidays = 'include_holidays',
}