export class SalaryCalculationModel {
    id: number;
    salary_number: string;
    selection_mode: string = 'month';
    month: number = null;
    from_date: Date;
    to_date: Date;
    filter_criteria: string;
    filter_employee: string;
    filter_employee_ids: string;
    filter_employee_type: string;
    filter_designation: string;
    filter_designation_ids: string;
    filter_department: string;
    filter_department_ids: string;
    filter_sponsor: string;
    exclude_zero_payable_days: boolean = true;
    employee_list: Array<EmployeeList>;
    selected_columns: string[] = [];
    default_global_object: any;
    employee_global_object: any;
    type_working_days: number = 0;
    day_or_hourly: number = 0;
    employee_type: string;
}

export class EmployeeList {
    id?: number;
    employee: number;
    employee_code: string;
    first_name: string;
    last_name: string;
    department: string;
    designation: string;
    no_of_days: number;
    basic: number;
    variable: number;
    ot: number;
    other_expense: number;
    other_incentive: number;
    tds: number;
    income_tax: number;
    bonus: number;
    advance: number;
    deductions_pay: number;
    advance_emi: number;
    gross_pay: number;
    net_pay: number;
    salary: number;
    from_date: Date;
    to_date: Date;
    base_gross_amount: number;
    base_deductions_amount: number;
    lop_amount: number;
    allowance_details = [];
    deduction_details = [];
    employer_pf_contribution: number;
    salary_status:    string = 'processing';
    sponsors:         string;
    leave_days:       number = 0;
    working_days:     number = 0;
    advance_balance:  number = 0;
    earned:           number = 0;
    arrears:          number = 0;
    remarks:          string;
    salary_breakdown:        any    = {};
    other_allowances:        number = 0;
    other_allowances_detail: any[]  = [];
    employer_esi_contribution: number;
}
