export enum InvoiceEnums {
  invoiceNo = "invoice_no",
  dueDate = "due_date",
  invoiceType = "invoice_type",
  invoiceDate = "invoice_date",
  source = "source",
  orderAcceptance = "order_acceptance",
  salesOrderRrofile = "sales_order_profile",
  serviceOrderProfile = "service_order_profile",
  deliveryChallan = 'delivery_challan',
  invoiceFor = "invoice_for",
  customerPoNo = "customer_po_no",
  customerPoDate = "customer_po_date",
  deliveryDate = "delivery_date",
  dispatchDocNo = "dispatch_doc_no",
  dispatchDocDate = "dispatch_doc_date",
  paymentTerms = 'payment_terms',
  deliveryTerms = 'delivery_terms',
  termsAndCondition = 'terms_and_condition',
  proforma_invoice = 'proforma_invoice',
  registeredAddress = 'registered_address',
  shipFrom = 'ship_from',
  shipFromAddress = 'ship_from_address',
  orderType = 'order_type',
  ciInvoiceType = 'ci_invoice_type',
  otherChargesCalculation = 'other_charge_calculation_type',

  customer = "customer",
  selectCustomer = "select_customer",
  bankDetail = "bank_detail",
  billToAddress = "bill_to_address",
  shipToAddress = "ship_to_address",
  phoneNumber = "phone_number",
  fax = "fax",
  taxNumber = "tax_number",
  website = "website",
  region = "region",
  pocName = "poc_name",
  pocEmail = "poc_email",
  pocMobile = "poc_mobile",

  totalQty = "total_qty",
  total = "total",
  discount = "discount",
  taxableAmount = "taxable_amount",
  cgst = "cgst",
  sgst = "sgst",
  igst = "igst",
  tcs = "tcs",
  adjustAmount = 'adjust_amount',
  adjustAmountLedger = "adjust_amount_ledger",
  adjustAmountLedgerName = "adjust_amount_ledger_name",
  grandTotal = "grand_total",
  freightCharges = "freight_charges",
  invoiceDetails = "invoice_details",
  incoiceTermsAndCondition = "invoice_terms_and_condition",
  invoicePocDetails = "invoice_poc_details",
  invoiceFileUpload = 'invoice_file_upload',
  billWiseReferenceDetails = "bill_wise_reference_details",
  stateCode = "state_code",
  country = "country",
  ledger = "ledger",
  cgstLedger = "cgst_ledger",
  cgstLedgerName = "cgst_ledger_name",
  igstLedger = "igst_ledger",
  igstLedgerName = "igst_ledger_name",
  sgstLedger = "sgst_ledger",
  sgstLedgerName = "sgst_ledger_name",
  tcsLedger = "tcs_ledger",
  tcsLedgerName = "tcs_ledger_name",
  isSez = "is_sez",
  isExport = "is_export",
  isInterstate = "is_interstate",
  conversion_rate = "conversion_rate",
  cif = "cif",
  totalAmountBaseCurrency = "total_amount_base_currency",
  lut_number = "lut_number",
  fromDate = "from_date",
  toDate = "to_date",
  need_eway_bill = "need_eway_bill",
  eway_bill_no = "eway_bill_no",
  generated_by = "generated_by",
  supply_type = "supply_type",
  mode = "mode",
  approx_distance = "approx_distance",
  transaction_type = "transaction_type",
  generated_date = "generated_date",
  valid_upto = "valid_upto",
  transporter_id = "transporter_id",
  transportation_name = "transportation_name",
  transportation_doc_no = "transportation_doc_no",
  transportation_date = "transportation_date",
  transportationRemarks = "transportation_remarks",
  vehicle_no = "vehicle_no",
  from_location = "from_location",
  cewb_no = "cewb_no",
  foreignTaxTypes = "foreign_tax_types",
  isForeign = "is_foreign",
  taxTypes = "tax_types",
  chargeValue = "charge_value",
  chargeDes = "charge_des",
  invoiceClaimDetails = "invoice_claim_details",
  roundOff = "round_off",
  vat = "vat",
  vatTreatment = 'vat_treatment',
  productService = 'product_service',
  anonymousBalanceAmount = "anonymous_balance_amount",
  anonymousReceivedAmount = "anonymous_received_amount",
  dispatchedThrough = 'dispatched_through',
  destination = 'destination',
  BillOfLadingLrRRNo = 'bill_of_lading_lr_rr_no',
  userCreated = 'user_created',
  formStatus = 'form_status',
  partyName = 'party_name',
  dcStatus = 'dc_status',
  lr_rr_date = 'lr_rr_date',
  lcNo = 'lc_no',
  lcDate = 'lc_date',
  note = 'note',
  billWiseTotalAmount = 'bill_wise_total_amount',
  amountType = 'amount_type',
  packing = 'packing',
  otherCharges = 'other_charges',
  otherChargesType = 'other_charges_type',
  countryOfOrigin = 'country_of_origin',
  portOfLoading = 'port_of_loading',
  netWeight = 'net_weight',
  grossWeight = 'gross_weight',
  partOfShipment = 'part_of_shipment',
  transportationTerms = 'transportation_terms',
  descriptionPacking = 'description_packing',
  modeOfTransportation = 'mode_of_transportation',
  cpiCurrency = 'cpi_currency',
  pgmRemark = 'pgm_remark',
  proformaInvoiceNumber = 'proforma_invoice_number',
  proformaInvoiceDate = 'proforma_invoice_date',
  noOfShipment = 'no_of_shipment',
  blNumber = 'bl_number',
  customerCommercialId = "customer_commercial_id",
  baseCurrency='base_currency',
  referenceNo='reference_no',
  created = 'created'



}

export enum InvoiceDetailsEnums {
  id = 'id',
  invoice = "invoice",
  partNumber = "part_number",

  drawingNumber = 'drawing_number',
  productName = "product_name",
  model = "model",
  brand = 'brand',
  hsn = "hsn",
  description = "description",
  unit = 'unit',
  unitName = 'unit_name',

  orderQty = 'order_qty',
  previousQty = 'previous_qty',
  shippingQty = 'shipping_qty',
  balanceQty = 'balance_qty',
  unitPrice = "unit_price",
  totalAmount = "total_amount",
  discount = "discount",
  discountAmount = "discount_amount",
  finalPrice = "final_price",
  taxableAmount = "taxable_amount",
  tax = "tax",
  taxValue = "tax_value",
  total = "total",
  vat = 'vat',
  vatValue = 'vat_value',
  final_total = 'final_total',
  total_amount_base_currency = 'total_amount_base_currency',
  invoiceSubProducts = "invoice_sub_products",
  invoiceSerialNumbers = 'invoice_serial_numbers',
  productService = 'product_service',

  // BOM
  itemCode = "item_code",
  project = 'project',
  projectCode = 'project_code',
  isSez = 'is_sez',

  projectDetails = 'project_details',
  projectCodes = 'project_codes',
  currency = 'currency',
  conversionRate = 'conversion_rate',
  priceInAed = "price_in_aed",
  customerPartNumber = 'customer_part_number',

  weight = 'weight',
  floorstatus = 'floor_status',
  uom='uom',


  invoiceDate = "invoice_date",
  invoiceNo = "invoice_no",
  cpiCurrency = 'cpi_currency',
  customerPoNo = "customer_po_no",


}

export enum InvoiceSubProductEnum {
  id = 'id',
  // invoiceDetails = 'invoice_details',
  partNumber = 'part_number',
  productName = 'product_name',
  model = 'model',
  hsn = 'hsn',
  quantity = 'quantity',
  shippingQuantity = 'shipping_qty',
  unit = 'unit',
  product = 'product',
}

export enum InvoiceTermsAndConditionEnums {
  invoice = "invoice",
  term = "term",
  description = "description"
}

export enum InvoiceSerialNumberEnum {
  id = 'id',
  // invoiceDetails = 'invoice_details',
  serialNumber = 'serial_number',
  custom = 'custom',
  type = 'type',
}

export enum SupplyType {
  O = 'Outward-Supply',
  I = 'Inward-Supply',
}

export const Mode: Record<string, string> = {
  '1': 'Road-1',
  '2': 'Rail-2',
  '3': 'Air-3',
  '4': 'Ship-4',
};

export enum TransactionType {
  R = 'Regular',
  O = 'ODC',
}

export enum InvoiceClaimDetailsEnums {
  // id = "id",
  invoice = "invoice",
  partNumber = "part_number",
  productName = "product_name",
  model = "model",
  brand = 'brand',
  hsn = "hsn",
  description = "description",
  qty = "qty",
  listPrice = "list_price",
  discount = "discount",
  netPrice = "net_price",
  poValue = "po_value",
  commissionAmount = "commission_amount",
  totalCommissionAmount = "total_commission_amount",
}

export enum InvoicePocDetailsEnums {
  id = "id",
  invoice = "invoice",
  poc = "poc",
  pocName = "poc_name",
  pocEmail = "poc_email",
  pocMobile = "poc_mobile",
  pocDepartment = "poc_department",
}
