export enum SalesQuotationEnums {
  // id = "id",
  quotationNo = "quotation_no",
  quotationType = "quotation_type",
  type = "type",
  salesInquiry = "sales_inquiry",
  opportunity = "opportunity",
  quotationDate = "quotation_date",
  quotationValidityDate = "quotation_validity_date",
  currency = "currency",
  quotationFor = "quotation_for",
  approverName = "approver_name",
  assignTo = "assign_to",
  status = "status",
  remarks = "remarks",
  customer = "customer",
  bankDetail = "bank_detail",
  customerCode = 'customer_code',
  customerFpoNo = 'customer_fpo_no',
  trn =  'trn',
  customerAddress =  'customer_address',
  customerEmail = 'customer_email',
  customerMobile = 'customer_mobile',
  modeofTransport = 'mode_of_transport',
  portOfDischarge = 'port_of_discharge',
  freightCharges = 'freight_charges',
  deliveryTerms = 'delivery_terms',
  billToAddress = "bill_to_address",
  shipToAddress = "ship_to_address",
  fax = "fax",
  website = "website",
  region = "region",
  pocName = "poc_name",
  pocEmail = "poc_email",
  pocMobile = "poc_mobile",
  pocDepartment = 'poc_department',
  paymentTerms = "payment_terms",
  eta = 'eta',
  etd = 'etd',

  totalQty = "total_qty",
  total = "total",
  discount = "discount",
  taxableAmount = "taxable_amount",
  cgst = "cgst",
  sgst = "sgst",
  igst = "igst",
  pf = "pf",
  pfAmount = "pf_amount",
  tcs = "tcs",
  adjustAmount = 'adjust_amount',
  grandTotal = "grand_total",
  cancelAmt = "cancel_amt",
  vatAmount = 'vat_amount',
  vatTreatment = 'vat_treatment',

  fileUpload = 'file_upload',

  deliveryPrice = "delivery_price",
  deliveryValidity = "delivery_validity",
  delivery = "delivery",
  deliveryInspection = "delivery_inspection",
  deliveryInsurance = "delivery_insurance",
  deliveryDispatchDetails = "delivery_dispatch_details",
  deliveryTransporter = "delivery_transporter",
  deliveryFreight = "delivery_freight",
  note = "note",

  editor = "editor",
  template = "template",

  salesQuotationDetails = "sales_quotation_details",
  salesFollowupDetails = "sales_followup_details",
  salesQuotationTermsAndCondition = "sales_quotation_terms_and_condition",
  paymentTermsDetails = "payment_terms_details",

  quotationStages = "quotation_stages",
  revisedCount = "revise_count",
  isRevised = "is_revised",
  baseReviseFk = "base_revised_fk",
  stateCode = "state_code",

  defaultEditorObject = "default_editor_object",
  totalAmount = "total_amount",

  customerCommercialId = "customer_commercial_id",
  countryOfOrigin = 'country_of_origin',
  portOfLoading = 'port_of_loading',
  destination = 'destination',
  netWeight = 'net_weight',
  grossWeight = 'gross_weight',
  partOfShipment = 'part_of_shipment',
  transportationTerms = 'transportation_terms',
  descriptionPacking = 'description_packing',
  modeOfTransportation = 'mode_of_transportation',
  cpiCurrency = 'cpi_currency',
  pgmRemark = 'pgm_remark',
  ref='ref',
  deliveryDate='delivery_date',
  packing='packing',
  otherCharges='other_charges',
  otherChargesType='other_charges_type',
  customerPoNo='customer_po_no',
  expiryDate='expiry_date',
  referenceNo='reference_no',
  approvalStatus='approval_status',
  quotationFileUpload = "quotation_file_upload",
  created = 'created',
  createdByName = 'created_by_name',

}

export enum SalesQuotationDetailsEnums {
  id = "id",
  salesQuotation = "sales_quotation",
  partNumber = "part_number",
  customerPartNumber = "customer_part_number",
  weight = "weight",
  productName = "product_name",
  hsn = "hsn",
  brand = "brand",
  model = "model",
  description = "description",
  quantity = "quantity",
  unit = "unit",
  unitPrice = "unit_price",
  currency = "currency",
  currency_rate = "currency_rate",
  form_unit_price = "form_unit_price",
  totalAmount = "total_amount",
  discount = "discount",
  discountAmount = "discount_amount",
  finalPrice = "final_price",
  taxableAmount = "taxable_amount",
  tax = "tax",
  taxValue = "tax_value",
  total = "total",
  primaryUnitName = "primary_units_name",
  unitName = 'unit_name',
  quotationNo = 'quotation_no',
  itemCode = "item_code",
  drawingNumber = "drawing_number",
  vatValue="vat_value",
  grossWeight = "gross_weight",
  uom = "uom",
  baseUnitPrice = "base_unit_price",
  postFsoQty = "post_fso_qty",
}

export enum SalesQuotationStagesEnums {
  date = "date",
  quotationNumber = "revised_quotation_number",
  technicalNegotiation = "technical_negotitaion",
  commercialNegotiation = "commercial_negotitaion",
  revisedQuotation = "revised_quotation",
  baseQuotation = "base_quotation"
}

export enum SalesQuotationFollowupEnums {
  followupDate = "followup_date",
  followupDetails = "followup_details",
  remarks = "remarks",
}

export enum SalesQuotationTermsAndConditionEnums {
  term = "term",
  description = "description"
}

export enum SalesQuotationPTEnums {
  salesQuotation = "sales_quotation",
  paymentTerms = "payment_terms",
  percentage = "percentage",
  value = "value",
}
