# Generated by Django 4.1.2 on 2026-09-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm_main', '0001_initial'),
        ('hrm_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplanning',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='tadadetailsimages',
            name='tada_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tada_details_images', to='hrm_main.tadadetails'),
        ),
        migrations.AddField(
            model_name='tadadetails',
            name='tada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tada_details', to='hrm_main.tada'),
        ),
    ]
