# Generated by Django 4.1.2 on 2026-09-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gratuityemployeeform',
            options={'permissions': [('custom_approval_stage_initiator', 'Can approve as initiator'), ('custom_approval_stage_HR', 'Can approve as HR'), ('custom_approval_stage_approver', 'Can approve as approver'), ('custom_approval_stage_secondary_approver', 'Can approve as secondary approver')]},
        ),
    ]
