# Generated by Django 4.1.2 on 2026-09-21 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm_master', '0001_initial'),
        ('hrm_main', '0002_initial'),
        ('master', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tada',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tada',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='tada',
            name='travel_planning',
            field=models.ManyToManyField(blank=True, default=[], related_name='tada_travel_planning', to='hrm_main.travelplanning'),
        ),
        migrations.AddField(
            model_name='salaryhold',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarycalculation',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashtransaction',
            name='expense_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_txns', to='hrm_main.expenseclaim'),
        ),
        migrations.AddField(
            model_name='pettycashtransaction',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='hrm_main.pettycashfund'),
        ),
        migrations.AddField(
            model_name='pettycashfundapprovalstages',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PettyCashFund_approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashfundapprovalstages',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PettyCashFund_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashfundapprovalstages',
            name='related_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='hrm_main.pettycashfund'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_funds', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='otsalarycalculation',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otemployeelist',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='otemployeelist',
            name='ot_salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ot_employee_list', to='hrm_main.otsalarycalculation'),
        ),
        migrations.AddField(
            model_name='historicaltravelplanninglog',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltravelplanninglog',
            name='travel_planning',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.travelplanning'),
        ),
        migrations.AddField(
            model_name='historicaltravelplanning',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicaltravelplanning',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltadadetailsimages',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltadadetailsimages',
            name='tada_details',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.tadadetails'),
        ),
        migrations.AddField(
            model_name='historicaltadadetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltadadetails',
            name='tada',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.tada'),
        ),
        migrations.AddField(
            model_name='historicaltada',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltada',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicaltada',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalaryhold',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalaryhold',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalarycalculation',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalarycalculation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpettycashtransaction',
            name='expense_claim',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.expenseclaim'),
        ),
        migrations.AddField(
            model_name='historicalpettycashtransaction',
            name='fund',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.pettycashfund'),
        ),
        migrations.AddField(
            model_name='historicalpettycashtransaction',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpettycashfund',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpettycashfund',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpettycashfund',
            name='holder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalotsalarycalculation',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalotsalarycalculation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalotemployeelist',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalotemployeelist',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalotemployeelist',
            name='ot_salary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.otsalarycalculation'),
        ),
        migrations.AddField(
            model_name='historicalgratuityemployeeform',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgratuityemployeeform',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalgratuityemployeeform',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgratuitycalculations',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalgratuitycalculations',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgratuitycalculations',
            name='monthly_sal_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.employeemonthlysalary'),
        ),
        migrations.AddField(
            model_name='historicalgratuity',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgracedetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgracedetails',
            name='shift',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.shiftmaster'),
        ),
        migrations.AddField(
            model_name='historicalfinalsettlementemployeemonthlydeductiondetails',
            name='final_settlement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.finalsettlement'),
        ),
        migrations.AddField(
            model_name='historicalfinalsettlementemployeemonthlydeductiondetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinalsettlementemployeemonthlyallowancedetails',
            name='final_settlement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.finalsettlement'),
        ),
        migrations.AddField(
            model_name='historicalfinalsettlementemployeemonthlyallowancedetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinalsettlement',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinalsettlement',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalfinalsettlement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaimlinktype',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaimlinktype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaimline',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.expenseclaimcategory'),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaimline',
            name='claim',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.expenseclaim'),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaimline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaimline',
            name='link_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.expenseclaimlinktype'),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaimline',
            name='linked_content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaimcategory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaimattachment',
            name='claim',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.expenseclaim'),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaimattachment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaim',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaim',
            name='claimant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaim',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaim',
            name='petty_cash_fund',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.pettycashfund'),
        ),
        migrations.AddField(
            model_name='historicalexpenseclaim',
            name='submitted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlysalary',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlysalary',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlysalary',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlydeductiondetails',
            name='grade_deduction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.grademonthlydeductiondetails'),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlydeductiondetails',
            name='gross_deductions',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.employeemonthlysalary'),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlydeductiondetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlydeductiondetails',
            name='salary_component',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.salarycomponents'),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlyallowancedetails',
            name='grade_allowance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.grademonthlyallowancedetails'),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlyallowancedetails',
            name='gross_earnings',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.employeemonthlysalary'),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlyallowancedetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployeemonthlyallowancedetails',
            name='salary_component',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.salarycomponents'),
        ),
        migrations.AddField(
            model_name='historicalemployeelist',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeelist',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployeelist',
            name='salary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.salarycalculation'),
        ),
        migrations.AddField(
            model_name='historicaldisciplinaryaction',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldisciplinaryaction',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicaldisciplinaryaction',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldeductiondetails',
            name='deduction_salary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.employeelist'),
        ),
        migrations.AddField(
            model_name='historicaldeductiondetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcareerletterimages',
            name='career_letter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.careerletter'),
        ),
        migrations.AddField(
            model_name='historicalcareerletterimages',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcareerletter',
            name='editor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.editor'),
        ),
        migrations.AddField(
            model_name='historicalcareerletter',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalcareerletter',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbonusdetails',
            name='bonus',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.bonus'),
        ),
        migrations.AddField(
            model_name='historicalbonusdetails',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalbonusdetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbonus',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbonus',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='historicalbonus',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalattendancestatusmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalattendanceimport',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalattendancedetails',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalattendancedetails',
            name='attendance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.attendanceimport'),
        ),
        migrations.AddField(
            model_name='historicalattendancedetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallowancedetails',
            name='allowance_salary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.employeelist'),
        ),
        migrations.AddField(
            model_name='historicalallowancedetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladvance',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladvance',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicaladvance',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gratuityemployeeformapprovalstages',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GratuityEmployeeForm_approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gratuityemployeeformapprovalstages',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GratuityEmployeeForm_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gratuityemployeeformapprovalstages',
            name='related_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='hrm_main.gratuityemployeeform'),
        ),
        migrations.AddField(
            model_name='gratuityemployeeform',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gratuityemployeeform',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='gratuitycalculations',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_gratuity', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='gratuitycalculations',
            name='monthly_sal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_sal_gratuity', to='hrm_main.employeemonthlysalary'),
        ),
        migrations.AddField(
            model_name='gracedetails',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grace_details', to='hrm_master.shiftmaster'),
        ),
        migrations.AddField(
            model_name='finalsettlementemployeemonthlydeductiondetails',
            name='final_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_settlement_deduction', to='hrm_main.finalsettlement'),
        ),
        migrations.AddField(
            model_name='finalsettlementemployeemonthlyallowancedetails',
            name='final_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_settlement_allowance', to='hrm_main.finalsettlement'),
        ),
        migrations.AddField(
            model_name='finalsettlement',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalsettlement',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='expenseclaimlinktype',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_claim_link_types', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='expenseclaimline',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claim_lines', to='hrm_main.expenseclaimcategory'),
        ),
        migrations.AddField(
            model_name='expenseclaimline',
            name='claim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hrm_main.expenseclaim'),
        ),
        migrations.AddField(
            model_name='expenseclaimline',
            name='link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claim_lines', to='hrm_main.expenseclaimlinktype'),
        ),
        migrations.AddField(
            model_name='expenseclaimline',
            name='linked_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claim_linked_objects', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='expenseclaimattachment',
            name='claim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hrm_main.expenseclaim'),
        ),
        migrations.AddField(
            model_name='expenseclaimapprovalstages',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExpenseClaim_approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseclaimapprovalstages',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExpenseClaim_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseclaimapprovalstages',
            name='related_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='hrm_main.expenseclaim'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='claimant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='petty_cash_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims', to='hrm_main.pettycashfund'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_expense_claims', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='employeemonthlysalary',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='employeemonthlysalary',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='employeemonthlydeductiondetails',
            name='grade_deduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_deduction', to='hrm_master.grademonthlydeductiondetails'),
        ),
        migrations.AddField(
            model_name='employeemonthlydeductiondetails',
            name='gross_deductions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gross_deductions', to='hrm_main.employeemonthlysalary'),
        ),
        migrations.AddField(
            model_name='employeemonthlydeductiondetails',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.salarycomponents'),
        ),
        migrations.AddField(
            model_name='employeemonthlyallowancedetails',
            name='grade_allowance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_earnings', to='hrm_master.grademonthlyallowancedetails'),
        ),
        migrations.AddField(
            model_name='employeemonthlyallowancedetails',
            name='gross_earnings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gross_earnings', to='hrm_main.employeemonthlysalary'),
        ),
        migrations.AddField(
            model_name='employeemonthlyallowancedetails',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.salarycomponents'),
        ),
        migrations.AddField(
            model_name='employeelist',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='employeelist',
            name='salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_list', to='hrm_main.salarycalculation'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_actions', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='deductiondetails',
            name='deduction_salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_deduction', to='hrm_main.employeelist'),
        ),
        migrations.AddField(
            model_name='careerletterimages',
            name='career_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_letter_images', to='hrm_main.careerletter'),
        ),
        migrations.AddField(
            model_name='careerletter',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.editor'),
        ),
        migrations.AddField(
            model_name='careerletter',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='bonusdetails',
            name='bonus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_details', to='hrm_main.bonus'),
        ),
        migrations.AddField(
            model_name='bonusdetails',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonus',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_master.grade'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceimport',
            unique_together={('date', 'b_id')},
        ),
        migrations.AddField(
            model_name='attendancedetails',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancedetails',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_details', to='hrm_main.attendanceimport'),
        ),
        migrations.AddField(
            model_name='allowancedetails',
            name='allowance_salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_gross', to='hrm_main.employeelist'),
        ),
        migrations.AddField(
            model_name='advance',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_master.employeemaster'),
        ),
    ]
