# Generated by Django 4.1.2 on 2026-09-23 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hrm_audit_fields.fields.uuid_auto_field
import hrm_audit_fields.models.audit_model_mixin
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_duns_number_branch_fax_number_branch_website_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleavepolicy',
            name='approval_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalleavepolicy',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalleavepolicy',
            name='approval_remarks',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalleavepolicy',
            name='approval_status',
            field=models.CharField(choices=[('NOT_APPROVED', 'Not Approved'), ('APPROVED', 'Approved'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalleavepolicy',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleavepolicy',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='approval_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='approval_remarks',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='approval_status',
            field=models.CharField(choices=[('NOT_APPROVED', 'Not Approved'), ('APPROVED', 'Approved'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=50),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricalGratuityConfigMaster',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=hrm_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=hrm_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', models.CharField(blank=True, max_length=200, null=True)),
                ('user_modified', models.CharField(blank=True, max_length=200, null=True)),
                ('uc_id', models.IntegerField(blank=True, default=None, null=True)),
                ('um_id', models.IntegerField(blank=True, default=None, null=True)),
                ('c_id', models.IntegerField(blank=True, default=None, null=True)),
                ('decimal', models.FloatField(blank=True, default=0.0, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True)),
                ('b_id', models.IntegerField(blank=True, default=None, null=True)),
                ('guid', hrm_audit_fields.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.')),
                ('is_active', models.BooleanField(default=True)),
                ('gratuity_formula_type', models.CharField(choices=[('UAE', 'UAE (MoHRE)'), ('INDIA', 'India (Gratuity Act 1972)')], default='UAE', help_text='Which gratuity law to apply for this branch', max_length=10)),
                ('gratuity_apply_statutory_cap', models.BooleanField(default=True, help_text='Enable statutory cap on total gratuity')),
                ('gratuity_cap_years', models.DecimalField(decimal_places=1, default=2.0, help_text='Cap ceiling in years of basic salary (UAE law=2, generous policy=3 etc.)', max_digits=4)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branch.branch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gratuity Config',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GratuityConfigMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=hrm_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=hrm_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', models.CharField(blank=True, max_length=200, null=True)),
                ('user_modified', models.CharField(blank=True, max_length=200, null=True)),
                ('uc_id', models.IntegerField(blank=True, default=None, null=True)),
                ('um_id', models.IntegerField(blank=True, default=None, null=True)),
                ('c_id', models.IntegerField(blank=True, default=None, null=True)),
                ('decimal', models.FloatField(blank=True, default=0.0, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True)),
                ('b_id', models.IntegerField(blank=True, default=None, null=True)),
                ('guid', hrm_audit_fields.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.')),
                ('is_active', models.BooleanField(default=True)),
                ('gratuity_formula_type', models.CharField(choices=[('UAE', 'UAE (MoHRE)'), ('INDIA', 'India (Gratuity Act 1972)')], default='UAE', help_text='Which gratuity law to apply for this branch', max_length=10)),
                ('gratuity_apply_statutory_cap', models.BooleanField(default=True, help_text='Enable statutory cap on total gratuity')),
                ('gratuity_cap_years', models.DecimalField(decimal_places=1, default=2.0, help_text='Cap ceiling in years of basic salary (UAE law=2, generous policy=3 etc.)', max_digits=4)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gratuity_config', to='branch.branch')),
            ],
            options={
                'verbose_name': 'Gratuity Config',
                'verbose_name_plural': 'Gratuity Configs',
            },
        ),
    ]
