# Generated by Django 4.1.2 on 2026-09-22 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hrm_main', '0003_initial'),
        ('branch', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereversalrequestapprovalstages',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LeaveReversalRequest_approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavereversalrequestapprovalstages',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LeaveReversalRequest_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavereversalrequestapprovalstages',
            name='related_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='hrm_master.leavereversalrequest'),
        ),
        migrations.AddField(
            model_name='leavereversalrequest',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavereversalrequest',
            name='delegated_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_delegated_reviewer', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='leavereversalrequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_request', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='leavereversalrequest',
            name='initiator_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_Initiator_reviewer', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='leavereversalrequest',
            name='leave_application',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverApplicationSals', to='hrm_master.leaveapplication'),
        ),
        migrations.AddField(
            model_name='leavereversalrequest',
            name='leave_entry',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reversals', to='hrm_master.leaveentry'),
        ),
        migrations.AddField(
            model_name='leavepolicydetail',
            name='leave_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policy_details', to='hrm_master.leavepolicy'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='type_of_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_main.attendancestatusmaster', verbose_name='Type of Leave'),
        ),
        migrations.AddField(
            model_name='leavemasterdetails',
            name='leave_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_master_details', to='hrm_master.leavemaster'),
        ),
        migrations.AddField(
            model_name='leavemasterdetails',
            name='leave_policy_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.leavepolicy'),
        ),
        migrations.AddField(
            model_name='leavemasterdetailbreakup',
            name='leave_master_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakup_details', to='hrm_master.leavemasterdetails'),
        ),
        migrations.AddField(
            model_name='leavemasterdetailbreakup',
            name='leave_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_details', to='hrm_master.leavepolicy'),
        ),
        migrations.AddField(
            model_name='leavemaster',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='leaveextension',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveextension',
            name='delegated_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_extension_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveextension',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_extensions', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='leaveextension',
            name='leave_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='hrm_master.leaveapplication'),
        ),
        migrations.AddField(
            model_name='leaveextension',
            name='leave_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='hrm_master.leaveentry'),
        ),
        migrations.AddField(
            model_name='leaveentryapprovalstages',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LeaveEntry_approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveentryapprovalstages',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LeaveEntry_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveentryapprovalstages',
            name='related_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='hrm_master.leaveentry'),
        ),
        migrations.AddField(
            model_name='leaveentry',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveentry',
            name='delegated_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegated_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveentry',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='leaveentry',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm_main.attendancestatusmaster'),
        ),
        migrations.AddField(
            model_name='leavedetails',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_details', to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='leaveapplicationapprovalstages',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LeaveApplication_approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplicationapprovalstages',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LeaveApplication_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplicationapprovalstages',
            name='related_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='hrm_master.leaveapplication'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='delegated_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='la_delegated_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.department'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='employee_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_applications_emp_code', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='holidaymaster',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalticketmaster',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalticketmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltickethistory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltickethistory',
            name='ticket_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.ticketmaster'),
        ),
        migrations.AddField(
            model_name='historicalshifttimings',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalshiftmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalarycomponents',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprofessionaltaxslab',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpreviousemploymentdetails',
            name='employee_previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalpreviousemploymentdetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleavereversalrequest',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleavereversalrequest',
            name='delegated_reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalleavereversalrequest',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalleavereversalrequest',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleavereversalrequest',
            name='initiator_reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalleavereversalrequest',
            name='leave_application',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.leaveapplication'),
        ),
        migrations.AddField(
            model_name='historicalleavereversalrequest',
            name='leave_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.leaveentry'),
        ),
        migrations.AddField(
            model_name='historicalleavepolicydetail',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleavepolicydetail',
            name='leave_policy',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.leavepolicy'),
        ),
        migrations.AddField(
            model_name='historicalleavepolicy',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalleavepolicy',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleavepolicy',
            name='type_of_leave',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.attendancestatusmaster', verbose_name='Type of Leave'),
        ),
        migrations.AddField(
            model_name='historicalleavemasterdetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleavemasterdetails',
            name='leave_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.leavemaster'),
        ),
        migrations.AddField(
            model_name='historicalleavemasterdetails',
            name='leave_policy_key',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.leavepolicy'),
        ),
        migrations.AddField(
            model_name='historicalleavemasterdetailbreakup',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleavemasterdetailbreakup',
            name='leave_master_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.leavemasterdetails'),
        ),
        migrations.AddField(
            model_name='historicalleavemasterdetailbreakup',
            name='leave_policy',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.leavepolicy'),
        ),
        migrations.AddField(
            model_name='historicalleavemaster',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalleavemaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleaveextension',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleaveextension',
            name='delegated_reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleaveextension',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalleaveextension',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleaveextension',
            name='leave_application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.leaveapplication'),
        ),
        migrations.AddField(
            model_name='historicalleaveextension',
            name='leave_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.leaveentry'),
        ),
        migrations.AddField(
            model_name='historicalleaveentry',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleaveentry',
            name='delegated_reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleaveentry',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalleaveentry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleaveentry',
            name='leave_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_main.attendancestatusmaster'),
        ),
        migrations.AddField(
            model_name='historicalleavedetails',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='historicalleavedetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleaveapplication',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleaveapplication',
            name='delegated_reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalleaveapplication',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.department'),
        ),
        migrations.AddField(
            model_name='historicalleaveapplication',
            name='employee_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalleaveapplication',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalholidaymaster',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalholidaymaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgrademonthlydeductiondetails',
            name='gross_deductions',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='historicalgrademonthlydeductiondetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgrademonthlydeductiondetails',
            name='salary_component',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.salarycomponents'),
        ),
        migrations.AddField(
            model_name='historicalgrademonthlyallowancedetails',
            name='gross_earnings',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='historicalgrademonthlyallowancedetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgrademonthlyallowancedetails',
            name='salary_component',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.salarycomponents'),
        ),
        migrations.AddField(
            model_name='historicalgrade',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='default_shift',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.shifttimings'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.department'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='designation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.designation'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='first_reporting_authority',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='groups',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='second_reporting_authority',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='shift_details',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.shiftmaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='shift_one_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.shiftmaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='shift_three_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.shiftmaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='shift_two_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.shiftmaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeemaster',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployeeletterimages',
            name='employee_letters',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeeletterimages',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployeedocumentsdetails',
            name='document_type_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.documenttypemaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeedocumentsdetails',
            name='employee_document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalemployeedocumentsdetails',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldocumenttypemaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldesignation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallowancemaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallowanceassignment',
            name='allowance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.allowancemaster'),
        ),
        migrations.AddField(
            model_name='historicalallowanceassignment',
            name='approved_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalallowanceassignment',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='historicalallowanceassignment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grademonthlydeductiondetails',
            name='gross_deductions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_gross_deductions', to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='grademonthlydeductiondetails',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.salarycomponents'),
        ),
        migrations.AddField(
            model_name='grademonthlyallowancedetails',
            name='gross_earnings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_gross_earnings', to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='grademonthlyallowancedetails',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.salarycomponents'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='default_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_shift', to='hrm_master.shifttimings'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.department'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.designation'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='first_reporting_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_reported', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm_master.grade'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='securityGroup', to='auth.group'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='second_reporting_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_reported', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='shift_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_master_details_employee', to='hrm_master.shiftmaster'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='shift_one_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_master_one_details_employee', to='hrm_master.shiftmaster'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='shift_three_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_master_three_details_employee', to='hrm_master.shiftmaster'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='shift_two_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_master_two_details_employee', to='hrm_master.shiftmaster'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='securityUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeletterimages',
            name='employee_letters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_letter_images', to='hrm_master.employeemaster'),
        ),
        migrations.AddField(
            model_name='employeedocumentsdetails',
            name='document_type_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='hrm_master.documenttypemaster'),
        ),
        migrations.AddField(
            model_name='employeedocumentsdetails',
            name='employee_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents_details', to='hrm_master.employeemaster'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('designation_name', 'b_id')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('department_name', 'b_id')},
        ),
        migrations.AlterUniqueTogether(
            name='allowancemaster',
            unique_together={('allowance_name', 'b_id')},
        ),
        migrations.AddField(
            model_name='allowanceassignment',
            name='allowance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hrm_master.allowancemaster'),
        ),
        migrations.AddField(
            model_name='allowanceassignment',
            name='approved_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowanceassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_assignments', to='hrm_master.employeemaster'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaymaster',
            unique_together={('date', 'to_date', 'b_id')},
        ),
    ]
