export const currency = [
    { "id": 1, "currency_name": "Bangladeshi Taka", "currency_code": "BDT" },
    { "id": 2, "currency_name": "United Arab Emirates Dirham", "currency_code": "AED" },
    { "id": 3, "currency_name": "Afghan Afghani", "currency_code": "AFN" },
    { "id": 4, "currency_name": "Albanian Lek", "currency_code": "ALL" },
    { "id": 5, "currency_name": "Armenian Dram", "currency_code": "AMD" },
    { "id": 6, "currency_name": "Netherlands Antillean Guilder", "currency_code": "ANG" },
    { "id": 7, "currency_name": "Angolan Kwanza", "currency_code": "AOA" },
    { "id": 8, "currency_name": "Argentine Peso", "currency_code": "ARS" },
    { "id": 9, "currency_name": "Australian Dollar", "currency_code": "AUD" },
    { "id": 10, "currency_name": "Aruban Florin", "currency_code": "AWG" },
    { "id": 11, "currency_name": "Azerbaijani Manat", "currency_code": "AZN" },
    { "id": 12, "currency_name": "Bosnia and Herzegovina Convertible Mark", "currency_code": "BAM" },
    { "id": 13, "currency_name": "Barbados Dollar", "currency_code": "BBD" },
    { "id": 14, "currency_name": "Bulgarian Lev", "currency_code": "BGN" },
    { "id": 15, "currency_name": "Bahraini Dinar", "currency_code": "BHD" },
    { "id": 16, "currency_name": "Burundian Franc", "currency_code": "BIF" },
    { "id": 17, "currency_name": "Bermudian Dollar", "currency_code": "BMD" },
    { "id": 18, "currency_name": "Brunei Dollar", "currency_code": "BND" },
    { "id": 19, "currency_name": "Boliviano", "currency_code": "BOB" },
    { "id": 20, "currency_name": "Bolivian Mvdol (Funds Code)", "currency_code": "BOV" },
    { "id": 21, "currency_name": "Brazilian Real", "currency_code": "BRL" },
    { "id": 22, "currency_name": "Bahamian Dollar", "currency_code": "BSD" },
    { "id": 23, "currency_name": "Bhutanese Ngultrum", "currency_code": "BTN" },
    { "id": 24, "currency_name": "Botswana Pula", "currency_code": "BWP" },
    { "id": 25, "currency_name": "Belarusian Ruble", "currency_code": "BYN" },
    { "id": 26, "currency_name": "Belize Dollar", "currency_code": "BZD" },
    { "id": 27, "currency_name": "Canadian Dollar", "currency_code": "CAD" },
    { "id": 28, "currency_name": "Congolese Franc", "currency_code": "CDF" },
    { "id": 29, "currency_name": "WIR Euro (Complementary Currency)", "currency_code": "CHE" },
    { "id": 30, "currency_name": "WIR Franc (Complementary Currency)", "currency_code": "CHW" },
    { "id": 31, "currency_name": "Unidad de Fomento (Funds Code)", "currency_code": "CLF" },
    { "id": 32, "currency_name": "Chilean Peso", "currency_code": "CLP" },
    { "id": 33, "currency_name": "Renminbi (Chinese) Yuan", "currency_code": "CNY" },
    { "id": 34, "currency_name": "Colombian Peso", "currency_code": "COP" },
    { "id": 35, "currency_name": "Unidad de Valor Real (UVR) (Funds Code)", "currency_code": "COU" },
    { "id": 36, "currency_name": "Costa Rican Colón", "currency_code": "CRC" },
    { "id": 37, "currency_name": "Cuban Convertible Peso", "currency_code": "CUC" },
    { "id": 38, "currency_name": "Cuban Peso", "currency_code": "CUP" },
    { "id": 39, "currency_name": "Cape Verdean Escudo", "currency_code": "CVE" },
    { "id": 40, "currency_name": "Czech Koruna", "currency_code": "CZK" },
    { "id": 41, "currency_name": "Djiboutian Franc", "currency_code": "DJF" },
    { "id": 42, "currency_name": "Danish Krone", "currency_code": "DKK" },
    { "id": 43, "currency_name": "Dominican Peso", "currency_code": "DOP" },
    { "id": 44, "currency_name": "Algerian Dinar", "currency_code": "DZD" },
    { "id": 45, "currency_name": "Egyptian Pound", "currency_code": "EGP" },
    { "id": 46, "currency_name": "Eritrean Nakfa", "currency_code": "ERN" },
    { "id": 47, "currency_name": "Ethiopian Birr", "currency_code": "ETB" },
    { "id": 48, "currency_name": "Euro", "currency_code": "EUR" },
    { "id": 49, "currency_name": "Fiji Dollar", "currency_code": "FJD" },
    { "id": 50, "currency_name": "Falkland Islands Pound", "currency_code": "FKP" },
    { "id": 51, "currency_name": "Pound Sterling", "currency_code": "GBP" },
    { "id": 52, "currency_name": "Georgian Lari", "currency_code": "GEL" },
    { "id": 53, "currency_name": "Ghanaian Cedi", "currency_code": "GHS" },
    { "id": 54, "currency_name": "Gibraltar Pound", "currency_code": "GIP" },
    { "id": 55, "currency_name": "Gambian Dalasi", "currency_code": "GMD" },
    { "id": 56, "currency_name": "Guinean Franc", "currency_code": "GNF" },
    { "id": 57, "currency_name": "Guatemalan Quetzal", "currency_code": "GTQ" },
    { "id": 58, "currency_name": "Guyanese Dollar", "currency_code": "GYD" },
    { "id": 59, "currency_name": "Hong Kong Dollar", "currency_code": "HKD" },
    { "id": 60, "currency_name": "Honduran Lempira", "currency_code": "HNL" },
    { "id": 61, "currency_name": "Croatian Kuna", "currency_code": "HRK" },
    { "id": 62, "currency_name": "Haitian Gourde", "currency_code": "HTG" },
    { "id": 63, "currency_name": "Hungarian Forint", "currency_code": "HUF" },
    { "id": 64, "currency_name": "Indonesian Rupiah", "currency_code": "IDR" },
    { "id": 65, "currency_name": "Israeli New Shekel", "currency_code": "ILS" },
    { "id": 66, "currency_name": "Indian Rupee", "currency_code": "INR" },
    { "id": 67, "currency_name": "Iraqi Dinar", "currency_code": "IQD" },
    { "id": 68, "currency_name": "Iranian Rial", "currency_code": "IRR" },
    { "id": 69, "currency_name": "Icelandic Króna", "currency_code": "ISK" },
    { "id": 70, "currency_name": "Jamaican Dollar", "currency_code": "JMD" },
    { "id": 71, "currency_name": "Jordanian Dinar", "currency_code": "JOD" },
    { "id": 72, "currency_name": "Japanese Yen", "currency_code": "JPY" },
    { "id": 73, "currency_name": "Kenyan Shilling", "currency_code": "KES" },
    { "id": 74, "currency_name": "Kyrgyzstani Som", "currency_code": "KGS" },
    { "id": 75, "currency_name": "Cambodian Riel", "currency_code": "KHR" },
    { "id": 76, "currency_name": "Comoro Franc", "currency_code": "KMF" },
    { "id": 77, "currency_name": "North Korean Won", "currency_code": "KPW" },
    { "id": 78, "currency_name": "South Korean Won", "currency_code": "KRW" },
    { "id": 79, "currency_name": "Kuwaiti Dinar", "currency_code": "KWD" },
    { "id": 80, "currency_name": "Cayman Islands Dollar", "currency_code": "KYD" },
    { "id": 81, "currency_name": "Kazakhstani Tenge", "currency_code": "KZT" },
    { "id": 82, "currency_name": "Lao Kip", "currency_code": "LAK" },
    { "id": 83, "currency_name": "Lebanese Pound", "currency_code": "LBP" },
    { "id": 84, "currency_name": "Sri Lankan Rupee", "currency_code": "LKR" },
    { "id": 85, "currency_name": "Liberian Dollar", "currency_code": "LRD" },
    { "id": 86, "currency_name": "Lesotho Loti", "currency_code": "LSL" },
    { "id": 87, "currency_name": "Libyan Dinar", "currency_code": "LYD" },
    { "id": 88, "currency_name": "Moroccan Dirham", "currency_code": "MAD" },
    { "id": 89, "currency_name": "Moldovan Leu", "currency_code": "MDL" },
    { "id": 90, "currency_name": "Malagasy Ariary", "currency_code": "MGA" },
    { "id": 91, "currency_name": "Macedonian Denar", "currency_code": "MKD" },
    { "id": 92, "currency_name": "Myanmar Kyat", "currency_code": "MMK" },
    { "id": 93, "currency_name": "Mongolian Tögrög", "currency_code": "MNT" },
    { "id": 94, "currency_name": "Macanese Pataca", "currency_code": "MOP" },
    { "id": 95, "currency_name": "Mauritanian Ouguiya", "currency_code": "MRU" },
    { "id": 96, "currency_name": "Mauritian Rupee", "currency_code": "MUR" },
    { "id": 97, "currency_name": "Maldivian Rufiyaa", "currency_code": "MVR" },
    { "id": 98, "currency_name": "Malawian Kwacha", "currency_code": "MWK" },
    { "id": 99, "currency_name": "Mexican Peso", "currency_code": "MXN" },
    { "id": 100, "currency_name": "Mexican Unidad de Inversion (UDI)", "currency_code": "MXV" },
    { "id": 101, "currency_name": "Malaysian Ringgit", "currency_code": "MYR" },
    { "id": 102, "currency_name": "Mozambican Metical", "currency_code": "MZN" },
    { "id": 103, "currency_name": "Namibian Dollar", "currency_code": "NAD" },
    { "id": 104, "currency_name": "Nigerian Naira", "currency_code": "NGN" },
    { "id": 105, "currency_name": "Nicaraguan Córdoba", "currency_code": "NIO" },
    { "id": 106, "currency_name": "Norwegian Krone", "currency_code": "NOK" },
    { "id": 107, "currency_name": "Nepalese Rupee", "currency_code": "NPR" },
    { "id": 108, "currency_name": "New Zealand Dollar", "currency_code": "NZD" },
    { "id": 109, "currency_name": "Omani Rial", "currency_code": "OMR" },
    { "id": 110, "currency_name": "Panamanian Balboa", "currency_code": "PAB" },
    { "id": 111, "currency_name": "Peruvian Sol", "currency_code": "PEN" },
    { "id": 112, "currency_name": "Papua New Guinean Kina", "currency_code": "PGK" },
    { "id": 113, "currency_name": "Philippine Peso", "currency_code": "PHP" },
    { "id": 114, "currency_name": "Pakistani Rupee", "currency_code": "PKR" },
    { "id": 115, "currency_name": "Polish Zloty", "currency_code": "PLN" },
    { "id": 116, "currency_name": "Paraguayan Guaraní", "currency_code": "PYG" },
    { "id": 117, "currency_name": "Qatari Riyal", "currency_code": "QAR" },
    { "id": 118, "currency_name": "Romanian Leu", "currency_code": "RON" },
    { "id": 119, "currency_name": "Serbian Dinar", "currency_code": "RSD" },
    { "id": 120, "currency_name": "Russian Ruble", "currency_code": "RUB" },
    { "id": 121, "currency_name": "Rwandan Franc", "currency_code": "RWF" },
    { "id": 122, "currency_name": "Saudi Riyal", "currency_code": "SAR" },
    { "id": 123, "currency_name": "Solomon Islands Dollar", "currency_code": "SBD" },
    { "id": 124, "currency_name": "Seychelles Rupee", "currency_code": "SCR" },
    { "id": 125, "currency_name": "Sudanese Pound", "currency_code": "SDG" },
    { "id": 126, "currency_name": "Swedish Krona/Kronor", "currency_code": "SEK" },
    { "id": 127, "currency_name": "Singapore Dollar", "currency_code": "SGD" },
    { "id": 128, "currency_name": "Saint Helena Pound", "currency_code": "SHP" },
    { "id": 129, "currency_name": "Sierra Leonean Leone", "currency_code": "SLL" },
    { "id": 130, "currency_name": "Somali Shilling", "currency_code": "SOS" },
    { "id": 131, "currency_name": "Surinamese Dollar", "currency_code": "SRD" },
    { "id": 132, "currency_name": "South Sudanese Pound", "currency_code": "SSP" },
    { "id": 133, "currency_name": "São Tomé and Príncipe Dobra", "currency_code": "STN" },
    { "id": 134, "currency_name": "Salvadoran Colón", "currency_code": "SVC" },
    { "id": 135, "currency_name": "Syrian Pound", "currency_code": "SYP" },
    { "id": 136, "currency_name": "Swazi Lilangeni", "currency_code": "SZL" },
    { "id": 137, "currency_name": "Thai Baht", "currency_code": "THB" },
    { "id": 138, "currency_name": "Tajikistani Somoni", "currency_code": "TJS" },
    { "id": 139, "currency_name": "Turkmenistan Manat", "currency_code": "TMT" },
    { "id": 140, "currency_name": "Tunisian Dinar", "currency_code": "TND" },
    { "id": 141, "currency_name": "Tongan Paʻanga", "currency_code": "TOP" },
    { "id": 142, "currency_name": "Turkish Lira", "currency_code": "TRY" },
    { "id": 143, "currency_name": "Trinidad and Tobago Dollar", "currency_code": "TTD" },
    { "id": 144, "currency_name": "New Taiwan Dollar", "currency_code": "TWD" },
    { "id": 145, "currency_name": "Tanzanian Shilling", "currency_code": "TZS" },
    { "id": 146, "currency_name": "Ukrainian Hryvnia", "currency_code": "UAH" },
    { "id": 147, "currency_name": "Ugandan Shilling", "currency_code": "UGX" },
    { "id": 148, "currency_name": "United States Dollar", "currency_code": "USD" },
    { "id": 149, "currency_name": "United States Dollar (Next Day) (Funds Code)", "currency_code": "USN" },
    { "id": 150, "currency_name": "Uruguay Peso en Unidades Indexadas (URUIURUI) (Funds Code)", "currency_code": "UYI" },
    { "id": 151, "currency_name": "Uruguayan Peso", "currency_code": "UYU" },
    { "id": 152, "currency_name": "Unidad Previsional", "currency_code": "UYW" },
    { "id": 153, "currency_name": "Uzbekistan Som", "currency_code": "UZS" },
    { "id": 154, "currency_name": "Venezuelan Bolívar Soberano", "currency_code": "VES" },
    { "id": 155, "currency_name": "Vietnamese Đồng", "currency_code": "VND" },
    { "id": 156, "currency_name": "Vanuatu Vatu", "currency_code": "VUV" },
    { "id": 157, "currency_name": "Samoan Tala", "currency_code": "WST" },
    { "id": 158, "currency_name": "CFA Franc BEAC", "currency_code": "XAF" },
    { "id": 159, "currency_name": "Silver (One Troy Ounce)", "currency_code": "XAG" },
    { "id": 160, "currency_name": "Gold (One Troy Ounce)", "currency_code": "XAU" },
    { "id": 161, "currency_name": "European Composite Unit (EURCO) (Bond Market Unit)", "currency_code": "XBA" },
    { "id": 162, "currency_name": "European Monetary Unit (E.M.U.-6) (Bond Market Unit)", "currency_code": "XBB" },
    { "id": 163, "currency_name": "European Unit of Account 9 (E.U.A.-9) (Bond Market Unit)", "currency_code": "XBC" },
    { "id": 164, "currency_name": "European Unit of Account 17 (E.U.A.-17) (Bond Market Unit)", "currency_code": "XBD" },
    { "id": 165, "currency_name": "East Caribbean Dollar", "currency_code": "XCD" },
    { "id": 166, "currency_name": "Special Drawing Rights", "currency_code": "XDR" },
    { "id": 167, "currency_name": "CFA Franc BCEAO", "currency_code": "XOF" },
    { "id": 168, "currency_name": "Palladium (One Troy Ounce)", "currency_code": "XPD" },
    { "id": 169, "currency_name": "CFP Franc (Franc Pacifique)", "currency_code": "XPF" },
    { "id": 170, "currency_name": "Platinum (One Troy Ounce)", "currency_code": "XPT" },
    { "id": 171, "currency_name": "SUCRE", "currency_code": "XSU" },
    { "id": 172, "currency_name": "Code Reserved for Testing", "currency_code": "XTS" },
    { "id": 173, "currency_name": "ADB Unit of Account", "currency_code": "XUA" },
    { "id": 174, "currency_name": "No Currency", "currency_code": "XXX" },
    { "id": 175, "currency_name": "Yemeni Rial", "currency_code": "YER" },
    { "id": 176, "currency_name": "South African Rand", "currency_code": "ZAR" },
    { "id": 177, "currency_name": "Zambian Kwacha", "currency_code": "ZMW" },
    { "id": 178, "currency_name": "Zimbabwean Dollar", "currency_code": "ZWL" }
];
